buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://plugins.gradle.org/m2/' }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:${loom_version}"
        classpath "gradle.plugin.com.matthewprenger:CurseGradle:1.4.0"
        classpath "com.modrinth.minotaur:Minotaur:2.+"
    }
}

apply plugin: 'fabric-loom'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'
apply plugin: 'com.matthewprenger.cursegradle'
apply plugin: 'com.modrinth.minotaur'

group = project.mod_group
version = project.mod_version

base {
    archivesName = "${project.mod_name}-${project.minecraft_version}-${project.loader}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(project.java_version.toInteger())
}

sourceSets{
    main {
        java {
            srcDirs("linkableapi/src/")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}"

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand(
            version: project.version
        )
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": project.mod_name,
            "Specification-Vendor": "troblecodings",
            "Specification-Version": project.version,
            "Implementation-Title": project.mod_name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "troblecodings",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

def key = System.getenv("CURSETOKEN")
if (key == null)
    key = 'dev'

curseforge {
    apiKey = key 

    project {
        id = project.curseforge_project_id

        changelog = file("changelog.md")
        changelogType = "markdown"

        releaseType = "release"

        addGameVersion project.minecraft_version
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")

    projectId = project.modrinth_project_id

    versionNumber = project.version
    versionName = "${project.mod_name} ${project.version}"

    uploadFile = jar

    gameVersions = [project.minecraft_version]
    loaders = [project.loader.toLowerCase()]

    changelog = file("changelog.md").text
}

tasks.register("publishMods") {
    dependsOn("curseforge", "modrinth")
}