plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
}

def ver = System.getenv("APPVEYOR_BUILD_VERSION")
if(ver == null)
	ver = "dev"
version = ver
group = 'com.troblecodings'
base {
	archivesName = 'TC-Redstone-26.1.2-Fabric'
}

sourceSets{
    main {
        java {
            srcDirs("linkableapi/src/")
        }
    }
}

def token = System.getenv("MODRINTHTOKEN")
if(token == null)
	token = 'dev'
modrinth {
    token = token
    projectId = 'rMlghquR'
    versionNumber = ver
	versionType = 'release'
    versionName = 'TC-Redstone-26.1.2-Fabric'
    uploadFile = jar
    gameVersions = ['26.1.2']
    loaders = ['fabric']
}

task publishToModSites {
    publishToModSites.dependsOn modrinth
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
			maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
	}
}
