# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Meta
mod_id=gircredstone
mod_name=TC-Redstone
mod_group=com.troblecodings
mod_author=MrTroble, Jeronimo
mod_version=3.2.4

# Minecraft
minecraft_version=1.18.2
loader=forge

# Forge
forge_version_main=40
forge_version=40.2.10

# Java
java_version=17

# Publishing
curseforge_project_id=503143
modrinth_project_id=rMlghquR