# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Mod Meta
mod_name=TC-Redstone
mod_group=com.troblecodings
mod_version=3.2.5

# Minecraft
minecraft_version=26.1.2

# Fabric
loader=Fabric
loader_version=0.19.2
loom_version=1.17-SNAPSHOT
fabric_api_version=0.147.0+26.1.2

# Java
java_version=25

# Publishing
curseforge_project_id=503143
modrinth_project_id=rMlghquR
