# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Meta
mod_name=TC-Redstone
mod_group=com.troblecodings
mod_version=3.2.4

# Minecraft
minecraft_version=1.16.5

# Fabric
loader=Fabric
yarn_mappings=1.16.5+build.10
loader_version=0.15.6
loom_version=1.13-SNAPSHOT
fabric_api_version=0.42.0+1.16

# Java
java_version=8

# Publishing
curseforge_project_id=503143
modrinth_project_id=rMlghquR