modLoader="javafml"
loaderVersion="["${forgeversion}",)"
issueTrackerURL="https://github.com/MrTroble/TCUtility/issues"
license="Apache License Version 2.0"

[[mods]]
modId="${modid}"
version="${version}"
displayName="${modname}"
displayURL="https://troblecodings.com/"
authors="${author}"
credits="German Immersive Railroading Community"
description="Wireless Redstone Mod - Works in unloaded Chunks TM."

[[dependencies.${modid}]]
    modId="forge" 
    mandatory=true 
    versionRange="[${forgeversion},)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion}]"
    ordering="NONE"
    side="BOTH"
