modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/German-Immersive-Railroading-Community/GIRC-Redstone/issues"
license="Apache License Version 2.0"

[[mods]]
modId="gircredstone"
version="${file.jarVersion}"
displayName="TC Redstone"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo"
description="Works in unloaded Chunks TM."

[[dependencies.gircredstone]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gircredstone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,)"
    ordering="NONE"
    side="BOTH"
