modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/MrTroble/Wireless-Redstone/issues"
license="Apache-2.0"

[[mods]]
modId="gircredstone"
version="${file.jarVersion}"
displayName="TC Redstone"
displayURL="https://troblecodings.com/"
authors="MrTroble, Jeronimo, Luex"
description="Works in unloaded Chunks TM."

[[dependencies.gircredstone]]
    modId="neoforge"
    type="required"
    versionRange="[21.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gircredstone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3]"
    ordering="NONE"
    side="BOTH"
