name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

  deploy:
    if: endswith(github.ref_name, 'master') && github.ref_protected && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      APPVEYOR_BUILD_VERSION: '3.2.2'
      CURSETOKEN: ${{ secrets.CURSETOKEN }}
      MODRINTHTOKEN: ${{ secrets.MODRINTHTOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Deploy
      uses: gradle/gradle-build-action@v2
      with:
        arguments: curseforge
